name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches: [main, develop]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    env:
      myNull: ${{ null }}
      myBoolean: ${{ false }}
      myIntegerNumber: ${{ 711 }}
      myFloatNumber: ${{ -9.2 }}
      myHexNumber: ${{ 0xff }}
      myExponentialNumber: ${{ -2.99e-2 }}
      myString: Mona the Octocat
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: echo "GitHub actor is ${{ github.actor }}"
      - run: npm install -g bats
      - run: bats -v
      - run: ./scripts/test.sh
      - run: |
          expr 1 + 1 > ./output.log
      - run: cat ./output.log
      - run: |
          echo $myNull
          echo $myBoolean
          echo $myIntegerNumber
          echo $myFloatNumber
          echo $myHexNumber
          echo $myExponentialNumber
          echo $myString
          echo ${{ contains('Hello world', 'llo') }}
          echo ${{ contains('Hello world', 'lsdjfoseflsef') }}
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: test-upload
      #     path: ./output.log
      # - uses: actions/download-artifact@v4
      #   with:
      #     name: test-upload
