name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches: [main, develop]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: echo "GitHub actor is ${{ github.actor }}"
      - run: npm install -g bats
      - run: bats -v
      - run: ./scripts/test.sh
      # - run: |
      #     expr 1 + 1 > ./output.log
      # - run: cat ./output.log
      # - uses: actions/upload-artifact@v4
      #   with:
      #     path: ./output.log